### ISSUE TITLE
Materialize theme oepncart 2.3

### ISSUE THREAD

**Issue by manwhocode** [trydalcoholic/opencart-materialize#110]
> Make sure that the problem is not related to the operation of the OpenCart and its settings. If the problem is related to the standard OpenCart functionality, make sure that there is no problem in the standard template and only appears in the Materialize Template.
> **If your question is not related to the problem in the work of the template or its modules, or you do not offer an idea for improving the work of the template, your question will be closed.**

## Describe your actions ##
If possible, add a link to your problem. Specify the steps to reproduce the problem.

## Expected behavior ##
What do you think should actually happen instead of a mistake?

## Possible solution of the problem ##
If you are proposing a solution, please describe it. If you just report a problem, you can skip this paragraph.

## Indicate if possible ##
* The name of your browser and its version;
* Version of the OpenCart and a translation for your language (if any);
* Screenshots.

**Comment by manwhocode** [comment]
Добрый день
Установил вашу тему работает в общем отлично
Есть некоторые проблемы
не полный перевод на Украинский язык
Не работает изменение цветов шаблона
opencart 2.3

**Comment by beroNL** [comment]
OC version 3.0.3.2 clean install and latest templatel
If i go to my checkout, fill in the forms and i go to shipment, it gives me a javascrpt popup with two times the message "Internat server error".
In my log files, the next lines apears:

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Twig_Error_Syntax: Unexpected "endfor" tag (expecting closing tag for the "if" tag defined near line 25) in "materialize/template/checkout/shipping_method.twig" at line 45. in /var/www/vhosts/xxx/httpdocs/system/library/template/Twig/Parser.php:172\nStack trace:\n#0 /var/www/vhosts/xxx/httpdocs/system/library/template/Twig/TokenParser/If.php(43): Twig_Parser->subparse(Array)\n#1 /var/www/vhosts/xxx/httpdocs/system/library/template/Twig/Parser.php(187): Twig_TokenParser_If->parse(Object(Twig_Token))\n#2 /var/www/vhosts/xxx/httpdocs/system/library/template/Twig/TokenParser/If.php(34): Twig_Parser->subparse(Array)\n#3 /var/www/vhosts/xxx/httpdocs/system/library/template/Twig/Parser.php(187): Twig_TokenParser_If->parse(Object(Twig_Token))\n#4 /var/www/vhosts/xxx/httpdocs/system/library/template/Twig/TokenParser/For.php(40): Twig_Parser->subparse(Array)\n#5 /var/www/vhosts/xxx.\n', referer: http://xxx/index.php?route=checkout/checkout
