### ISSUE TITLE
not apply colours and cart, compare icons in opencart 3 themes

### ISSUE THREAD

**Issue by skillbhushan** [trydalcoholic/opencart-materialize#113]
Hi,

I applied the materialize themes for open cart 3.0.2.0 version, it is installed but when I change the themes color it is not changing in those themes.
I am using the latest chrome usually, but I tried on other browsers also getting the same error.

when I inspect on the page there is found on the issue in HTML code. The below code is generated automatically.

</script></div></div></div></main><footer class="page-footerblue-grey darken-3grey-text text-lighten-3"><div class="container"><div class="row"><div class="col l6 s12grey-text text-lighten-3">

I change below :

</script></div></div></div></main><footer class="page-footer blue-grey darken-3 grey-text text-lighten-3"><div class="container"><div class="row"><div class="col l6 s12 grey-text text-lighten-3">

its themes apply changes and shown properly.

**Comment by multimal** [comment]
there is an error in the main database at the template creator:
Warning: mysqli::__construct(): (HY000/2002): Connection refused in /var/www/www-root/data/www/materialize.myefforts.ru/public_html/system/library/db/mysqli.php on line 7Warning: DB\MySQLi::__construct(): Couldn't fetch mysqli in /var/www/www-root/data/www/materialize.myefforts.ru/public_html/system/library/db/mysqli.php on line 10Warning: DB\MySQLi::__construct(): Couldn't fetch mysqli in /var/www/www-root/data/www/materialize.myefforts.ru/public_html/system/library/db/mysqli.php on line 10
Fatal error: Uncaught Exception: Error: <br />Error No: in /var/www/www-root/data/www/materialize.myefforts.ru/public_html/system/library/db/mysqli.php:10 Stack trace: #0 /var/www/www-root/data/www/materialize.myefforts.ru/public_html/system/library/db.php(31): DB\MySQLi->__construct('127.0.0.1', 'materialize.mye...', 'WsmTOfC|bsB*#pP...', 'materialize.mye...', '3310') #1 /var/www/www-root/data/www/materialize.myefforts.ru/public_html/system/framework.php(80): DB->__construct('mysqli', '127.0.0.1', 'materialize.mye...', 'WsmTOfC|bsB*#pP...', 'materialize.mye...', '3310') #2 /var/www/www-root/data/www/materialize.myefforts.ru/public_html/system/startup.php(104): require_once('/var/www/www-ro...') #3 /var/www/www-root/data/www/materialize.myefforts.ru/public_html/index.php(19): start('catalog') #4 {main} thrown in /var/www/www-root/data/www/materialize.myefforts.ru/public_html/system/library/db/mysqli.php on line 10
