### ISSUE TITLE
Добавление mega-menu

### ISSUE THREAD

**Issue by iron-zorin** [trydalcoholic/opencart-materialize#92]
Пытаюсь добавить меню https://opencart-3x.ru/modul-universalnoe-mega-menyu-dlya-opencart-3
Выдаёт критическую ошибку
`Uncaught ReferenceError: $ is not defined
    at index.php?route=common/home:44
(anonymous) @ index.php?route=common/home:44
`
И предупреждения
`script.js:2 jQuery.Deferred exception: Cannot set property 'tabIndex' of null TypeError: Cannot set property 'tabIndex' of null
    at s.value (../catalog/view/theme/materialize/js/script.js:5:39943)
    at new s (../catalog/view/theme/materialize/js/script.js:5:35303)
    at Function.value (../catalog/view/theme/materialize/js/script.js:5:11906)
    at Function.value (../catalog/view/theme/materialize/js/script.js:5:43289)
    at w.fn.init.jQuery.fn.(anonymous function) [as dropdown] (../catalog/view/theme/materialize/js/script.js:5:12862)
    at HTMLDocument.<anonymous> (../catalog/view/theme/materialize/js/script.js:226:11)
    at l (../catalog/view/theme/materialize/js/script.js:2:29375)
    at c (../catalog/view/theme/materialize/js/script.js:2:29677) undefined
w.Deferred.exceptionHook @ script.js:2
c @ script.js:2
setTimeout (async)
(anonymous) @ script.js:2
u @ script.js:2
fireWith @ script.js:2
fire @ script.js:2
u @ script.js:2
fireWith @ script.js:2
ready @ script.js:2
setTimeout (async)
(anonymous) @ script.js:2
(anonymous) @ script.js:2
(anonymous) @ script.js:2
script.js:5 Uncaught TypeError: Cannot set property 'tabIndex' of null
    at s.value (script.js:5)
    at new s (script.js:5)
    at Function.value (script.js:5)
    at Function.value (script.js:5)
    at w.fn.init.jQuery.fn.(/oc3/anonymous function) [as dropdown] (../catalog/view/theme/materialize/js/script.js:5:12862)
    at HTMLDocument.<anonymous> (script.js:226)
    at l (script.js:2)
    at c (script.js:2)`

44 строка в index.php?route=common/home имеет такой вид
`$(document).ready(function(){`

Добавил в ваш хедер из дефолтного
`<script src="catalog/view/javascript/jquery/jquery-2.1.1.min.js" type="text/javascript"></script>`

Первая критическая ошибка пропала, но всё остальное - нет

 

Можете помочь?

**Comment by trydalcoholic** [comment]
Здравствуйте!
Данный модуль не является часть шаблона Materialize.
Пожалуйста, обратитесь к разработчику модуля.
